# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = StlFileReader
DESTDIR = ../x64/Debug
CONFIG += debug console c++17
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = StlFileReader.rc
HEADERS += ./Widget.h
SOURCES += ./Widget.cpp \
    ./main.cpp
FORMS += ./Widget.ui
